###
POST http://localhost:3102/me-connecter
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "admin1234"
}

###
POST http://localhost:3102/api/auth/local/register
Content-Type: application/json

{
  "username": "test@gmail.com",
  "email": "test@gmail.com",
  "password": "admin1234"
}

###
POST http://localhost:1337/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjUtMDEtMTZUMTA6MDY6MTQuMzcyWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDEtMTZUMTA6MDY6MTQuMzcyWiIsImlhdCI6MTczNzAyMjAyM30.bkBy-EDRFrKxCUWyXLqIwswXNdGNc4tm_vMlgXhcRwk

{
  "currentPassword": "admin1234",
  "password": "admin12",
  "passwordConfirmation": "admin12"
}



###
POST http://localhost:1337/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0b210b20iLCJlbWFpbCI6InRob21hc2xhZm9yZ2VAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wN1QwOTowODo1Mi43NzdaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wN1QwOToxMToxNC42MDdaIiwiaWF0IjoxNzAxOTQwMzIxfQ.tuzC-PVTqhF4qFaYOhC4wPxvK48EvNqtV-dh0moZLvI

###
GET http://localhost:1337/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjUtMDEtMTZUMTA6MDY6MTQuMzcyWiIsInVwZGF0ZWRBdCI6IjIwMjUtMDEtMTZUMTA6MDY6MTQuMzcyWiIsImlhdCI6MTczNzAyMjAyM30.bkBy-EDRFrKxCUWyXLqIwswXNdGNc4tm_vMlgXhcRwk


###
GET http://localhost:3102/miels
Authorization: `Believe ${token}`
        
###
GET http://localhost:3102/miels/4
Authorization: `Believe ${token}`

###
POST http://localhost:3102/miels
Authorization: `Believe ${token}`
Content-Type: 'application/json',

{ 
  "nom": "Miel de test 2", 
  "description": "Description de test 2", 
  "prix": 102 
}

###
PUT http://localhost:3102/miels/4/prix/10
Content-Type: 'application/json',
Authorization: `Believe ${token}`

{ 
  "nom": "Miel de test à jour", 
  "description": "Description de test à jour" 
}

###
DELETE http://localhost:3102/miels/4
Content-Type: 'application/json',
Authorization: `Believe ${token}`

###
GET http://localhost:3102/miels?tags=bio,sapin
Authorization: `Believe ${token}`

###
GET http://localhost:3102/miels?tags=bio,lavande,montagne
Authorization: `Believe ${token}`

###
POST http://localhost:3102/tags
Content-Type: 'application/json',
Authorization: `Believe ${token}`

{ "tag": "accacia" }